### ISSUE TITLE
New versions not published to Chef Supermarket

### ISSUE THREAD

**Issue by mrdziuban** [willejs/chef-amazon-ecs-agent#8]
The latest version on Chef Supermarket is 0.1.1, which depends on `'docker', '~> 0.0.36'`, while the latest revision in this repo depends on `'docker', '~> 2.2.9'`. Could you publish the latest version to the supermarket? Thanks!

**Comment by willejs** [comment]
Hi @mrdziuban Il push this now.
Im not super happy with this cookbook, it works, but im not quite using it in production yet, and i think theres alot i could do to it to make it alot better.

**Comment by willejs** [comment]
pushed @mrdziuban

**Comment by mrdziuban** [comment]
Thanks!
